# Generated by Django 4.2.7 on 2023-12-13 07:07

import config.extended_json
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_alter_room_options_room_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_names', models.JSONField(decoder=config.extended_json.ExtendedJSONDecoder, default=set, encoder=config.extended_json.ExtendedJSONEncoder)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='online_user_set',
            field=models.ManyToManyField(blank=True, related_name='joined_rooms', through='chats.RoomMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
